version: '3'
services:
  db:
    image: mariadb:10.2
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: rekisync
      MYSQL_PASSWORD: rekisync
      MYSQL_DATABASE: rekisync_development
    ports:
      - "3306:3306"
    volumes:
      - ./docker/tmp/mysql:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
volumes:
  data:
    driver: local